apiVersion: v1
kind: Pod
metadata:
  name: sample-pod
  namespace: web-apps
  labels:
     app: nginx
spec:
  securitycontext: 
    runAsUser: 1000                       #Default UID for containers 
    runAsGroup: 3000                      #Default GID for containers
    fsGroup: 2000                         #GID for mounted volumes
  initContainers:
    - name: init-download
      image: 
      command: ['sh', '-c', 'echo Initcontainer' ]
      volumeMounts:
        - name: some-volume
          mountPath: /tmp/init
  containers:
  - name: nginx
    image: nginx:1.28.0
    imagePullPolicy: IfNotPresent
    Ports:
      - containerPort: 80 
    env: 
      - name: Environment
        value: dev  
    resources:
      requests:
        memory: "100Mi"
        cpu: "100m"
      limits:
        memory: "200Mi"
        cpu: "500m"
    readinessProbe: 
      httpGet: 
        path: /
        port: 80 
      initialDelaySeconds: 5
      periodSeconds: 10
    livnessProbe:
      httpGet: 
        path: /
        port: 80 
      initialDelaySeconds: 10
      periodSeconds: 15  
    volumeMounts:
      - name: config-volume
        mountPath: /etc/nginx/conf.d
      - name: temp-volume
        mountPath: /tmp/init        
